name: app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.20.2

  # Fonts And Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  # Logger
  logger: ^2.0.2

  # Database And Cache
  shared_preferences: ^2.0.15
  # isar: ^3.1.0+1
  # isar_flutter_libs: ^3.1.0+1

  # State Management
  flutter_riverpod: ^2.1.1
  riverpod_annotation: ^2.0.4
  riverpod: ^2.1.3
  hooks_riverpod: ^2.3.6
  flutter_hooks: ^0.21.2
  riverpod_state: ^0.1.1

  # Models
  freezed_annotation: ^3.0.0
  json_annotation: ^4.7.0
  retrofit: '>=4.0.0 <5.0.0'

  # Routing
  go_router: ^16.0.0
  responsive_framework: ^1.0.0
  dio: ^5.0.1

  # UI
  flutter_svg: ^2.0.2
  
  # Animations
  animated_text_kit: ^4.2.2
  
  # Utils
  gap: ^3.0.0
  form_validator: ^2.1.1
  since_date: ^0.0.2
  infinite_scroll_pagination: ^4.0.0
  image_picker: ^1.0.4
  awesome_dio_interceptor: ^1.0.0
  url_launcher: ^6.1.10
  cached_network_image: ^3.2.3
  image_cropper: ^9.0.0
  timeago: ^3.4.0
  country_code_picker: ^3.0.0
  # ffmpeg_kit_flutter: ^6.0.2

  path_provider: 2.1.5
  flutter_native_splash: ^2.4.6
  icons_launcher: ^3.0.1
  uuid: ^4.5.1
  mobkit_dashed_border: ^0.0.8
  file_picker: ^10.2.1
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  # isar_generator: ^3.1.0+1
  custom_lint:
  riverpod_lint: ^2.0.4
  # go_router_builder: 2.8.0
  retrofit_generator: any
  build_runner: any
  flutter_gen_runner: any
  # build_verify: any
  riverpod_generator: ^2.1.6
  flutter_lints: ^6.0.0
  freezed: ^3.0.4
  json_serializable: ^6.5.4
  change_app_package_name: ^1.1.0


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/app_icons/
    - assets/svg/
    - assets/images/
    - assets/lottie/

flutter_native_splash:
  color: "#EFEFEF"             # Light background
  color_dark: "#676767"        # Dark background

  image: assets/images/titanium_logo_light.png
  image_dark: assets/images/titanium_logo_dark.png
  
  branding: assets/app_icons/branding_light.png
  branding_dark: assets/app_icons/branding_dark.png
  branding_mode: bottom


  android: true
  ios: true
  web: false

  android_gravity: center
  ios_content_mode: center

  # Padding for branding image from bottom

  branding_bottom_padding: 28

  android_12:
    image: assets/images/titanium_logo_light.png
    image_dark: assets/images/titanium_logo_dark.png

    color: "#EFEFEF"
    color_dark: "#676767"

    icon_background_color: "#EFEFEF"    
    icon_background_color_dark: "#676767"   
    branding: assets/app_icons/branding_light.png
    branding_dark: assets/app_icons/branding_dark.png

    # even if heaven and earth are turned upside down, dont use this  
    #branding_dark_android: assets/app_icons/branding_dark.png
# icons_launcher:
#   image_path: "assets/app_icons/app_icon_light.png"
#   platforms:
#     android:
#       enable: true
#       image_path: "assets/app_icons/app_icon_light.png"
#       notification_image: "assets/app_icons/app_icon_light.png"
#       adaptive_background_color: '#EFEFEF'
#       #adaptive_background_image: "assets/app_icons/app_icon_light.png"
#       adaptive_foreground_image: "assets/app_icons/app_icon_light.png"
#       adaptive_round_image: "assets/app_icons/app_icon_light.png"
#       adaptive_monochrome_image: "assets/app_icons/app_icon_dark.png"
#     ios:
#       enable: true
#       image_path: "assets/app_icons/app_icon_light.png"
#       dark_path: "assets/app_icons/app_icon_dark.png"




arb_directories:
  source: lib/l10n
  output: lib/l10n/app_arb
  locales:
    - en
    - ar
    - ja
    - ku


flutter_assets:
  assets_path: assets/
  output_path: lib/utils/constants/
  filename: assets.dart
  

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true